FROM ubuntu:20.04
RUN apt-get -y update

RUN apt-get install python=3.8 \
git \ 
make \
build-essentials \
python3-pip

RUN git clone https://github.com/STASYA00/boat_tracker.git

RUN pip3 install --upgrade pip3

RUN cd code

RUN pip3 install -r requirements.txt

RUN chmod u+x main.py

