FROM nvidia/cuda:11.5.1-base-ubuntu20.04

RUN apt update && apt install tzdata -y
ENV TZ="Europe/Stockholm"

RUN apt-get install -y python3 \
git \ 
make \
build-essential \
python3-pip \
ffmpeg \
libsm6 \
libxext6

RUN git clone https://github.com/STASYA00/boat_tracker.git

RUN pip3 install --upgrade pip

WORKDIR "./boat_tracker"

RUN pip3 install -r ./requirements.txt

RUN chmod u+x src/main.py

COPY 1.mp4 src/tests/1.mp4

CMD sh
